In [1]:
import emoji


In [2]:
print(type(emoji.UNICODE_EMOJI))

<class 'dict'>


In [3]:
print(emoji.emojize(":angry_face:"))
print(emoji.emojize(":OK_hand_light_skin_tone:"))

😠
👌🏻


In [4]:
#emoji.EMOJI_UNICODE

In [5]:
import pandas as pd

In [6]:
data = pd.read_csv("train_emoji.csv",header=None)

In [7]:
data.head(n=10)

0  1   2     3
0              never talk to me again  3 NaN   NaN
1     I am proud of your achievements  2 NaN   NaN
2      It is the worst day in my life  3 NaN   NaN
3                    Miss you so much  0 NaN   [0]
4                        food is life  4 NaN   NaN
5                      I love you mum  0 NaN   NaN
6                Stop saying bullshit  3 NaN   NaN
7  congratulations on your acceptance  2 NaN   NaN
8         The assignment is too long   3 NaN   NaN
9                   I want to go play  1 NaN   [3]

In [8]:
emoji_dict = {
    0:":beating_heart:",
    1:":baseball:",
    2:":beaming_face_with_smiling_eyes:",
    3:":disappointed_face:",
    4:":fork_and_knife:"    
}

In [9]:
for ix in emoji_dict.values():
    print(emoji.emojize(ix))

💓
⚾
😁
😞
🍴


In [10]:
X_train = data[0]
Y_train = data[1]

In [11]:
print(X_train.shape)

(132,)


In [12]:
print(Y_train.shape)

(132,)


In [13]:
print(X_train[0])

never talk to me again


In [14]:
print(emoji.emojize(emoji_dict[Y_train[0]]))

😞


In [15]:
#convert every sentence into a list of words
for ix in range(132):
    X_train[ix] = X_train[ix].lower().split()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [16]:
print(X_train[1])

['i', 'am', 'proud', 'of', 'your', 'achievements']


In [17]:
def read_glove_vecs(glove_file):
    with open(glove_file, 'r',encoding='utf8') as f:
        words = set()
        word_to_vec_map = {}
        for line in f:
            line = line.strip().split()
            curr_word = line[0]
            words.add(curr_word)
            word_to_vec_map[curr_word] = np.array(line[1:], dtype=np.float64)
        
        i = 1
        words_to_index = {}
        index_to_words = {}
        for w in sorted(words):
            words_to_index[w] = i
            index_to_words[i] = w
            i = i + 1
    return words_to_index, index_to_words, word_to_vec_map


In [18]:
import numpy as np
words_to_index, index_to_words, word_to_vec_map = read_glove_vecs("glove6b50dtxt/glove.6B.50d.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'glove6b50dtxt/glove.6B.50d.txt'

In [19]:
word_to_vec_map["happy"].shape

NameError: name 'word_to_vec_map' is not defined

In [20]:
def avg_vector(words):
    
    ans = word_to_vec_map[words[0]]
   # print(ans)
    for i in range(1,len(words)):
        ans = np.add(ans,word_to_vec_map[words[i]])
    ans = ans/float(len(words))
    return ans    

In [21]:
ans = avg_vector(X_train[0])

NameError: name 'word_to_vec_map' is not defined

In [22]:
X_numbers = np.zeros((132,50))

In [23]:
for i in range(X_train.shape[0]):
    X_numbers[i] = avg_vector(X_train[i])

NameError: name 'word_to_vec_map' is not defined

In [24]:
print(X_numbers.shape)
print(X_numbers)

(132, 50)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
from keras.models import Sequential
from keras.layers import Dense,Input,Activation
from keras.utils import to_categorical


Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [26]:
model = Sequential()
# Build neural network
model.add(Dense(10, activation='relu', input_shape=(50,)))
model.add(Dense(5, activation='softmax'))

NameError: name 'Sequential' is not defined

In [27]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

NameError: name 'model' is not defined

In [28]:
print(Y_train.shape)
Y_onehot = to_categorical(Y_train)
print(Y_onehot.shape)

(132,)


NameError: name 'to_categorical' is not defined

In [29]:
print(Y_train[0])
print(Y_onehot[0])

3


NameError: name 'Y_onehot' is not defined

In [30]:
model.fit(X_numbers,Y_onehot,epochs=100)

NameError: name 'model' is not defined

In [31]:
i = 7
print(data[0][i])

['congratulations', 'on', 'your', 'acceptance']


In [32]:
output = np.argmax(model.predict(X_numbers),axis=1)

NameError: name 'model' is not defined

In [33]:
print(Y_train[:10])

0    3
1    2
2    3
3    0
4    4
5    0
6    3
7    2
8    3
9    1
Name: 1, dtype: int64


In [34]:
np.sum(output==Y_train)

NameError: name 'output' is not defined

In [35]:
text = "i love this movie"

avg_v = avg_vector(text.split())
print(avg_v.shape)
avg_v= avg_v.reshape(1,50)
print(avg_v.shape)

NameError: name 'word_to_vec_map' is not defined

In [36]:
emoji_label_predict = np.argmax(model.predict(avg_v))

NameError: name 'model' is not defined

In [37]:
print(emoji_label_predict)
print(emoji.emojize(emoji_dict[emoji_label_predict]))

NameError: name 'emoji_label_predict' is not defined